config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :projects
  resources :daily_updates
  resources :leaves do
    member do
      patch 'update_status'
    end
  end
  devise_for :users
  resources :employees
  get '/tables', to: 'home#tables'
  post 'change_role', to: 'employees#change_role'
  # get 'edit', to: 'employess#edit'
  # patch 'update', to: 'employees#update'
  # get 'demo', to: 'users#new_user'
  # post 'test', to: 'users#create_user'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  
  def index 
    # @employee = User.all
    # @employee = User.all.page(params[:page]).per(5)
    @employee = User.order(:name).page params[:page]
  end 

  def change_role
    @employee = User.find(params[:id])
    @employee.remove_role :employee if @employee.has_role? :employee
    @employee.add_role :admin unless @employee.has_role? :admin
    flash[:alert] = "admin have been sucessfully changed the role."
    redirect_to employees_path
  end

  def new
    @employee = User.new
  end
  
  def create
    @employee = User.new(user_params)

    if @employee.save
      redirect_to employees_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @employee = User.find(params[:id])
  end

  def update
    @employee = User.find(params[:id])

    if @employee.update(user_params)
      redirect_to employees_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @employee = User.find(params[:id])
    @employee.destroy
    flash[:alert] = "User was successfully deleted."
    redirect_to employees_path
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :phone, :salary, :joining_date, :password,:date_of_birth, :organization_id)
    end
end

app/views/employees/_form.html.erb
<%= render "home/navbar" %>
<%= render "home/leftsidebar" %>

<div class="main">
	<!-- MAIN CONTENT -->
	<div class="main-content">
		<div class="container-fluid">
			<h3 class="page-title"></h3>
			<div class="row">
        <div class="col-md-6">
				<!-- BASIC TABLE -->
				  <div class="panel">
					  <div class="panel-heading">
						  <h3 class="panel-title">Create New Employee</h3>
					  </div>
					  <div class="panel-body">
            
              <div class="field" > 
                <%= f.label :name %>
                <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
              </div>
              <div style="color: red">
              <% if @employee.errors[:name].any? %>
                <div class="error">
                  <%= @employee.errors[:name].join(", ") %>
                </div>
              <% end %>
              </div>
              
              <div class="field" >
                <%= f.label :email %>
                <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
              </div>
              <% if @employee.errors[:email].any? %>
                <div class="error">
                  <%= @employee.errors[:email].join(", ") %>
                </div>
              <% end %>
              

              <div class="field">
                <%= f.label :phone %>
                <%= f.text_field :phone, autofocus: true, autocomplete: "phone" %>
              </div>
              <% if @employee.errors[:phone].any? %>
                <div class="error">
                  <%= @employee.errors[:phone].join(", ") %>
                </div>
              <% end %>

              <div class="field">
                <%= f.label :salary %>
                <%= f.text_field :salary, autofocus: true, autocomplete: "salary" %>
              </div>
              <% if @employee.errors[:salary].any? %>
                <div class="error">
                  <%= @employee.errors[:salary].join(", ") %>
                </div>
              <% end %>

              <div class="field">
                <%= f.label :Joining_date %>
                <%= f.date_field :joining_date, autofocus: true, autocomplete: "joining_date" %>
              </div>
              <% if @employee.errors[:joining_date].any? %>
                <div class="error">
                  <%= @employee.errors[:joining_date].join(", ") %>
                </div>
              <% end %>

              <div class="field">
                <%= f.label :date_of_birth %>
                <%= f.date_field :date_of_birth, autofocus: true, autocomplete: "date_of_birth" %>
              </div>
              <% if @employee.errors[:date_of_birth].any? %>
                <div class="error">
                  <%= @employee.errors[:date_of_birth].join(", ") %>
                </div>
              <% end %>

              <div class="field">
                <%= f.label :password %>
                <%= f.password_field :password, autocomplete: "new-password" %>
              </div>
              <% if @employee.errors[:password].any? %>
                <div class="error">
                  <%= @employee.errors[:password].join(", ") %>
                </div>
              <% end %>

              <div class="field">
                <%= f.hidden_field :organization_id, value: current_user.organization_id %>
              </div>

              
            
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

  

app/views/employees/edit.html.erb
<%= form_for @employee, url: { controller: 'employees', action: 'update'} do |f| %>
  <%= render 'form',f: f%>
  <div class="col-md-12 text-end"><br />
    <%= f.button "update" %>
  </div>
<% end %>

app/views/employees/index.html.erb
<%= render "home/navbar" %>
<%= render "home/leftsidebar" %>
<!-- MAIN -->
<div class="main">
	<!-- MAIN CONTENT -->
	<% if flash[:alert] %>
		<div class="alert"><%= flash[:alert] %></div>
	<% end %>
	<div class="main-content">
		<div class="container-fluid">
			<h3 class="page-title"></h3>
			<div class="row">
				<!-- BASIC TABLE -->
				<div class="panel">
					<div class="panel-heading">
						<h3 class="panel-title">Employee deatils</h3>
						<ul class="nav navbar-nav navbar-right">
							<%= link_to new_employee_path, class: "btn btn-primary" do %>
								<i class="fa fa-user-plus"></i> Add User
							<% end %>
						</ul>
					</div>
					<div class="panel-body">
						<table class="table">
							<thead>
								<tr>
									<th>Id</th>
									<th>Name</th>
									<th>Email</th>
									<th>Phone</th>
									<th>Salary</th>
									<th>Joining_date</th>
									<th>Date_of_birth</th>
									<th>Role</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
								<% @employee.each do |employee| %>
									<tr>
										<td><%= employee.id %></td>
										<td><%= employee.name %></td>
										<td><%= employee.email %></td>
										<td><%= employee.phone %></td>
										<td><%= employee.salary %></td>
										<td><%= employee.joining_date&.strftime("%d-%m-%Y") %></td>
										<td><%= employee.date_of_birth&.strftime("%d-%m-%Y") %></td>
										<td><%= button_to 'Change role', change_role_path(id: employee.id), method: :post %></td>
										<td><%= link_to edit_employee_path(employee.id) do %><i class='fa fa-pencil-square-o'></i><% end %>    
											<%= link_to  employee_path(employee),data: { "turbo-method": :delete, turbo_confirm: 'Are you sure?'} do %><i class='fa fa-trash'></i></td><% end %>
									</tr>
								<% end %>
							</tbody>
						</table>
					</div>
				</div>
				<!-- END BASIC TABLE -->
				<%= paginate @employee %>
			</div>
		</div>
	</div>
<!-- END MAIN CONTENT -->
</div>
<!-- END MAIN -->
<div class="clearfix"></div>
	<footer>
		<div class="container-fluid">
			<p class="copyright">&copy; 2017 <a href="https://www.themeineed.com" target="_blank">Theme I Need</a>. All Rights Reserved.</p>
		</div>
	</footer>
</div>
<!-- END WRAPPER -->
<!-- Javascript -->
<%= javascript_include_tag 'jquery/jquery.min' %>
<%= javascript_include_tag 'bootstrap/js/bootstrap.min' %>
<%= javascript_include_tag 'jquery-slimscroll/jquery.slimscroll.min' %>
<%= javascript_include_tag 'scripts/klorofil-common' %>

app/views/employees/new.html.erb
<%= form_for @employee, url: employees_url, method: :post do |f| %>
  <%= render 'form' , f: f%></br >
  <div class="col-md-12 text-end">
    <%= f.button "Create" %>
  </div>
<% end %>