config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :projects
  resources :daily_updates
  resources :leaves do
    member do
      patch 'update_status'
    end
  end
  devise_for :users
  resources :employees
  get '/tables', to: 'home#tables'
  post 'change_role', to: 'employees#change_role'
  # get 'edit', to: 'employess#edit'
  # patch 'update', to: 'employees#update'
  # get 'demo', to: 'users#new_user'
  # post 'test', to: 'users#create_user'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/admin/_admin_leftbar.html.erb
<!-- LEFT SIDEBAR -->
		<div id="sidebar-nav" class="sidebar">
			<div class="sidebar-scroll">
				<nav>
					<ul class="nav">
						<li><i class="fa fa-home"><%= link_to 'Dashboard',root_path %></i> </li>
						<li><i class='fa fa-users'><%= link_to 'Employees',employees_path %></i> </li>
						<li><a href="#" class=""><%= link_to "Leaves", leaves_url %></a></li>
						<li><a href="#" class=""><%= link_to 'Daily_Upadtes',daily_updates_path %></a></li>
						<li><a href="#" class=""><%= link_to 'Projects',projects_path %></a></li>
						<li><a href="#" class=""><i class="lnr lnr-alarm"></i> <span>Notifications</span></a></li>
						<li>
							<a href="#subPages" data-toggle="collapse" class="collapsed"><i class="lnr lnr-file-empty"></i> <span>Pages</span> <i class="icon-submenu lnr lnr-chevron-left"></i></a>
							<div id="subPages" class="collapse ">
								<ul class="nav">
									<li><a href="#" class="">Profile</a></li>
									<li><a href="#" class="">Login</a></li>
									<li><a href="#" class="">Lockscreen</a></li>
								</ul>
							</div>
						</li>
						<li><%=  link_to "Tables", "#" %><i class="lnr lnr-dice"></i> <span>Tables</span></a></li>
						<li><a href="#" class=""><i class="lnr lnr-text-format"></i> <span>Typography</span></a></li>
						<li><a href="#" class=""><i class="lnr lnr-linearicons"></i> <span>Icons</span></a></li>
					</ul>
				</nav>
			</div>
		</div>
		<!-- END LEFT SIDEBAR -->
    

app/views/admin/_admin_navbar.html.erb
<head>
	<title>Dashboard | Klorofil - Free Bootstrap Dashboard Template</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
	<!-- VENDOR CSS -->
	<%= stylesheet_link_tag "bootstrap/css/bootstrap.min" %>
	<%= stylesheet_link_tag "font-awesome/css/font-awesome.min" %>
	<%= stylesheet_link_tag "linearicons/style" %>
	<%= stylesheet_link_tag "chartist/css/chartist-custom" %>



  <!-- MAIN CSS -->
	<%= stylesheet_link_tag "main" %>
	
	<!-- FOR DEMO PURPOSES ONLY.  should remove this in your project -->
	<%= stylesheet_link_tag "demo" %>
	
	<!-- GOOGLE FONTS -->
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
	<!-- ICONS -->
	<link rel="apple-touch-icon" sizes="76x76" href="assets/images/apple-icon.png">
	<link rel="icon" type="image/png" sizes="96x96" href="assets/images/favicon.png">

</head>


	<!-- WRAPPER -->
	<div id="wrapper">
		<!-- NAVBAR -->
		<nav class="navbar navbar-default navbar-fixed-top">
		<div class="brand">
			<a href="#"><a class="">Employee_management_system</a>
			<%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
		</div>

		<div class="container-fluid">
			<div class="navbar-btn">
				<button type="button" class="btn-toggle-fullwidth"><i class="lnr lnr-arrow-left-circle"></i></button>
			</div>
			<form class="navbar-form navbar-left">
				<div class="input-group">
					<input type="text" value="" class="form-control" placeholder="Search dashboard...">
					<span class="input-group-btn"><button type="button" class="btn btn-primary">Go</button></span>
				</div>
			</form>
			<div class="navbar-btn navbar-btn-right">
			</div>
			<div id="navbar-menu">
				<ul class="nav navbar-nav navbar-right">
					
					<li class="dropdown">
						<ul class="dropdown-menu">
							<li><a href="#">Basic Use</a></li>
							<li><a href="#">Working With Data</a></li>
							<li><a href="#">Security</a></li>
							<li><a href="#">Troubleshooting</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= image_tag "user.png", alt:"Avatar", class:"img-circle" %>
						<span><%= current_user.email %></span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
						<ul class="dropdown-menu">
							<li><a href="#"><i class="lnr lnr-user"></i> <span>My Profile</span></a></li>
							<li><a href="#"><i class="lnr lnr-envelope"></i> <span>Message</span></a></li>
							<li><a href="#"><i class="lnr lnr-cog"></i> <span>Settings</span></a></li>
							<li><a href="#"><i class="lnr lnr-exit"></i> <span><%= button_to "Sign out", destroy_user_session_path, method: :delete %></span></a></li>
						</ul>
					</li>
					<!-- <li>
						<a class="update-pro" href="https://www.themeineed.com/downloads/klorofil-pro-bootstrap-admin-dashboard-template/?utm_source=klorofil&utm_medium=template&utm_campaign=KlorofilPro" title="Upgrade to Pro" target="_blank"><i class="fa fa-rocket"></i> <span>UPGRADE TO PRO</span></a>
					</li> -->
				</ul>
			</div>
		</div>
	</nav>
		<!-- END NAVBAR -->


	