config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :projects
  resources :daily_updates
  resources :leaves do
    member do
      patch 'update_status'
    end
  end
  devise_for :users
  resources :employees
  get '/tables', to: 'home#tables'
  post 'change_role', to: 'employees#change_role'
  # get 'edit', to: 'employess#edit'
  # patch 'update', to: 'employees#update'
  # get 'demo', to: 'users#new_user'
  # post 'test', to: 'users#create_user'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/daily_update.rb
class DailyUpdate < ApplicationRecord
  belongs_to :user
  belongs_to :organization
end

app/controllers/daily_updates_controller.rb
class DailyUpdatesController < ApplicationController
  before_action :set_daily_update, only: %i[ show edit update destroy ]

  # GET /daily_updates or /daily_updates.json
  def index
    @daily_updates = DailyUpdate.all
  end

  # GET /daily_updates/1 or /daily_updates/1.json
  def show
  end

  # GET /daily_updates/new
  def new
    @daily_update = DailyUpdate.new
  end

  # GET /daily_updates/1/edit
  def edit
  end

  # POST /daily_updates or /daily_updates.json
  def create
    @daily_update = DailyUpdate.new(daily_update_params)

    respond_to do |format|
      if @daily_update.save
        format.html { redirect_to daily_update_url(@daily_update), notice: "Daily update was successfully created." }
        format.json { render :show, status: :created, location: @daily_update }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @daily_update.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /daily_updates/1 or /daily_updates/1.json
  def update
    respond_to do |format|
      if @daily_update.update(daily_update_params)
        format.html { redirect_to daily_update_url(@daily_update), notice: "Daily update was successfully updated." }
        format.json { render :show, status: :ok, location: @daily_update }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @daily_update.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /daily_updates/1 or /daily_updates/1.json
  def destroy
    @daily_update.destroy

    respond_to do |format|
      format.html { redirect_to daily_updates_url, notice: "Daily update was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_daily_update
      @daily_update = DailyUpdate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def daily_update_params
      params.require(:daily_update).permit( :description, :start_time, :end_time, :project_name, :user_id, :organization_id).merge(user_id: current_user.id, organization_id: current_user.organization_id )
    end
end

app/helpers/daily_updates_helper.rb
module DailyUpdatesHelper
end

app/views/daily_updates/_daily_update.html.erb
<div id="<%= dom_id daily_update %>">
</div>

app/views/daily_updates/_form.html.erb
<%= form_with(model: daily_update) do |form| %>
  <% if daily_update.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(daily_update.errors.count, "error") %> prohibited this daily_update from being saved:</h2>

      <ul>
        <% daily_update.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, autofocus: true, autocomplete: "description" %>
  </div>
  <% if @daily_update.errors[:description].any? %>
    <div class="error">
      <%= @daily_update.errors[:description].join(", ") %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :project_name %>
    <%= form.text_field :project_name, autofocus: true, autocomplete: "project_name" %>
  </div>
  <% if @daily_update.errors[:project_name].any? %>
    <div class="error">
      <%= @daily_update.errors[:project_name].join(", ") %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.date_field :start_time, autofocus: true, autocomplete: "start_time" %>
  </div>
  <% if @daily_update.errors[:start_time].any? %>
    <div class="error">
      <%= @daily_update.errors[:start_time].join(", ") %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.date_field :end_time, autofocus: true, autocomplete: "end_time" %>
  </div>
  <% if @daily_update.errors[:end_time].any? %>
    <div class="error">
      <%= @daily_update.errors[:end_time].join(", ") %>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/daily_updates/edit.html.erb
<h1>Editing daily update</h1>

<%= render "form", daily_update: @daily_update %>

<br>

<div>
  <%= link_to "Show this daily update", @daily_update %> |
  <%= link_to "Back to daily updates", daily_updates_path %>
</div>

app/views/daily_updates/index.html.erb
<!-- MAIN -->
<div class="main">
	<!-- MAIN CONTENT -->
	<% if flash[:alert] %>
		<div class="alert"><%= flash[:alert] %></div>
	<% end %>
	<div class="main-content">
		<div class="container-fluid">
			<h3 class="page-title"></h3>
			<div class="row">
				<!-- BASIC TABLE -->
				<div class="panel">
					<div class="panel-heading">
						<h3 class="panel-title">Leaves list</h3>
						<ul class="nav navbar-nav navbar-right">
							<%= link_to new_daily_update_path, class: "btn btn-primary" do %>
								Add New Leave
							<% end %>
						</ul>
					</div>
					<div class="panel-body">
						<table class="table">
							<thead>
								<tr>
									<th>Id</th>
									<% if current_user.is_admin? %>
										<th>User Name</th>
									<% end %>
									<th>leave_type</th>
									<th>description</th>
									<th>from_date</th>
									<th>to_date</th>	
									<th>status</th>
									<% if current_user.is_admin? %>
										<th>Action</th>
									<% end %>
								</tr>
							</thead>
							<tbody>
							
						</tbody>
					</table>
				</div>
			</div>
				<!-- END BASIC TABLE -->
				

app/views/daily_updates/new.html.erb
<h1>New daily update</h1>

<%= render "form", daily_update: @daily_update %>

<br>

<div>
  <%= link_to "Back to daily updates", daily_updates_path %>
</div>

app/views/daily_updates/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @daily_update %>

<p>description=<%= @daily_update.description %></p>
<p>start_time=<%= @daily_update.start_time %></p>
<p>to_date=<%= @daily_update.end_time %></p>
<p>project_name =<%= @daily_update.project_name %></p>

<div>
  <%= link_to "Edit this daily update", edit_daily_update_path(@daily_update) %> |
  <%= link_to "Back to daily updates", daily_updates_path %>

  <%= button_to "Destroy this daily update", @daily_update, method: :delete %>
</div>